import type { LauncherConfig } from './config'

/** Minimal KEY=VALUE parser for tests/round-trips (ignores comments + blanks). */
export function parseEnv(text: string): Record<string, string> {
	const out: Record<string, string> = {}
	for (const raw of text.split('\n')) {
		const line = raw.trim()
		if (!line || line.startsWith('#')) continue
		const eq = line.indexOf('=')
		if (eq === -1) continue
		out[line.slice(0, eq)] = line.slice(eq + 1)
	}
	return out
}

/**
 * Anthropic API keys are prefixed `sk-ant-`; every other shape (OpenAI's `sk-` /
 * `sk-proj-`) we route to OpenAI. Both providers satisfy the default `smart` chat
 * alias (Anthropic as primary, OpenAI via fallback), so a single wizard field that
 * auto-detects the provider is enough to unblock first-use chat.
 */
export function providerKeyVar(key: string): 'ANTHROPIC_API_KEY' | 'OPENAI_API_KEY' {
	return /^sk-ant-/i.test(key) ? 'ANTHROPIC_API_KEY' : 'OPENAI_API_KEY'
}

/**
 * Append a LQ_AI_GATEWAY_MASTER_KEY line to an existing .env if it lacks one,
 * preserving every line already present (notably a manually-added provider key).
 * Idempotent: returns the text unchanged when the key is already there. This is
 * the migration path for installs created before the BYOK master key existed —
 * we never rewrite the whole file (renderEnv would drop a hand-added key).
 */
export function ensureMasterKeyLine(envText: string, masterKey: string): string {
	if (/^LQ_AI_GATEWAY_MASTER_KEY=/m.test(envText)) return envText
	const sep = envText.length === 0 || envText.endsWith('\n') ? '' : '\n'
	return `${envText}${sep}LQ_AI_GATEWAY_MASTER_KEY=${masterKey}\n`
}

/**
 * Render the .env the release compose (docker-compose.release.yml) expects. Keys mirror
 * .env.release.example exactly. Values are minted secrets / known ports / a single
 * wizard-supplied provider key — never free-text that needs quoting — so a plain
 * KEY=VALUE form is safe.
 *
 * NOTE (launcher decision L-3, revised 2026-06-21): the first-run wizard now collects an
 * OPTIONAL provider key and we write it here (ANTHROPIC_API_KEY or OPENAI_API_KEY, by
 * prefix). The original L-3 said "no keys here; add them in-app via Configure (BYOK)",
 * but the shipped launcher has no Configure→provider-keys page and doesn't set
 * LQ_AI_GATEWAY_MASTER_KEY, so a fresh .dmg install had no way to make chat work. The
 * stack still boots fully healthy with NO key — the field is optional — chat just stays
 * unanswerable until a key is present. A malformed key (blank, or containing internal
 * whitespace) is dropped rather than written, so we never emit a corrupt .env line.
 */
export function renderEnv(cfg: LauncherConfig): string {
	const { secrets: s, ports: p } = cfg

	const lines = [
		'# Generated by LQ.AI for Mac — do not edit by hand.',
		'',
		'# Image selection',
		`LQ_AI_IMAGE_TAG=${cfg.imageTag}`,
		`LQ_AI_IMAGE_NAMESPACE=${cfg.imageNamespace}`,
		'',
		'# Host ports (loopback-bound by the compose defaults)',
		`WEB_HOST_PORT=${p.web}`,
		`API_HOST_PORT=${p.api}`,
		`GATEWAY_HOST_PORT=${p.gateway}`,
		`POSTGRES_HOST_PORT=${p.postgres}`,
		`REDIS_HOST_PORT=${p.redis}`,
		`MINIO_API_HOST_PORT=${p.minioApi}`,
		`MINIO_CONSOLE_HOST_PORT=${p.minioConsole}`,
		'',
		'# Required backend secrets',
		'POSTGRES_DB=lq_ai',
		'POSTGRES_USER=lq_ai',
		`POSTGRES_PASSWORD=${s.POSTGRES_PASSWORD}`,
		'MINIO_ROOT_USER=lq_ai',
		`MINIO_ROOT_PASSWORD=${s.MINIO_ROOT_PASSWORD}`,
		'S3_ACCESS_KEY=lq_ai',
		`S3_SECRET_KEY=${s.S3_SECRET_KEY}`,
		`LQ_AI_GATEWAY_KEY=${s.LQ_AI_GATEWAY_KEY}`,
		`JWT_SECRET=${s.JWT_SECRET}`,
		// Enables the gateway's runtime BYOK provider-key store (encrypts keys at rest);
		// without it the in-app "Provider keys" page gets 400 failed_precondition.
		`LQ_AI_GATEWAY_MASTER_KEY=${s.LQ_AI_GATEWAY_MASTER_KEY}`
	]

	// Optional, wizard-supplied. Drop blank or whitespace-containing values so a
	// fat-fingered paste never produces an unparseable KEY=VALUE line.
	const key = cfg.providerKey?.trim()
	if (key && !/\s/.test(key)) {
		lines.push('', '# Provider key (optional; collected by the first-run wizard).', `${providerKeyVar(key)}=${key}`)
	}

	lines.push('')
	return lines.join('\n')
}
